apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your.git.repo/cluster.git
    targetRevision: HEAD
    path: cluster/infra/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
