
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bitwarden
  namespace: infra-secrets
spec:
  provider:
    bitwarden:
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
